### ISSUE TITLE
A14_in to

### ISSUE THREAD

**Issue by ToddlerPichu** [NaomiMod/Rent-A-Hero-No1#102]
On the newest revision, instances of " to " seem to be fixed so good job on that... I ran into this instance still of the word "into" being separated as two words "in to"
![shot329](https://user-images.githubusercontent.com/41944249/193426617-bd12c391-b285-42ec-b26e-55aa58243e68.png)

**Comment by VincentNLOBJ** [comment]
Luckily only A14, A20 and A24 are affected, I'll make sure to fix the remaining ones you'll find ;)

**Comment by ToddlerPichu** [comment]
👍

**Comment by VincentNLOBJ** [comment]
Done! Hopefully the last stray ` to ` left
