### ISSUE TITLE
F02_call name Danger_!!

### ISSUE THREAD

**Issue by ToddlerPichu** [NaomiMod/Rent-A-Hero-No1#106]
If you are in the hero show looking for Alice and lose the announcer tells the crowd to call your name and everyone shouts "Danger" instead of your name. There are also 2 exclamation marks "!!" that spill over to the 2nd line
![shot363](https://user-images.githubusercontent.com/41944249/193434274-7d82484f-d34a-44c2-9ca4-8238859c5a8e.png)
![shot365](https://user-images.githubusercontent.com/41944249/193434275-a5d9157c-5d7d-4759-a0cb-245338353e03.png)

**Comment by VincentNLOBJ** [comment]
Danger might had been a leftover from XB text, fixed.
