### ISSUE TITLE
A02_Game doesn't ask for hero name

### ISSUE THREAD

**Issue by ToddlerPichu** [NaomiMod/Rent-A-Hero-No1#11]
I believe the game is supposed to ask for your hero name after the first fight handing out flyers, yet it goes to a Shopping menu instead (on a side note winning the fight the blonde women will call you your entered last name, while losing the fight she will call you by your entered first name)
![shot30](https://user-images.githubusercontent.com/41944249/191740100-03ff3b43-9184-444d-bae1-a2b15df0e996.png)

**Comment by VincentNLOBJ** [comment]
This a critical bug, thanks for reporting!

**Comment by VincentNLOBJ** [comment]
Fixed, the first crit bug goes down!
