### ISSUE TITLE
A20_s to le

### ISSUE THREAD

**Issue by ToddlerPichu** [NaomiMod/Rent-A-Hero-No1#110]
Another instance of "to" having spaces before and after it, on revision 0.12
![shot375](https://user-images.githubusercontent.com/41944249/193468931-f0669d73-ccfe-4d98-914d-1c3404e0b4e2.png)

**Comment by VincentNLOBJ** [comment]
Fixed! 👍

**Comment by ToddlerPichu** [comment]
Just now or previously? Because I know a lot of instances in previous revision were resolved with the new build I have... but I still ran into this one just now
