### ISSUE TITLE
A20_MacroSOFT inconsistencies 

### ISSUE THREAD

**Issue by ToddlerPichu** [NaomiMod/Rent-A-Hero-No1#115]
I've noticed in many places in the game there is a habit of typing out MarcoSOFT in different ways... sometimes it is with capitals or without and sometimes it is with a space or without. Doesn't matter which spelling is used, but I think these should be unified.. though I do think MacroSOFT looks best and matches the buildings sign.
![shot393](https://user-images.githubusercontent.com/41944249/193471453-e6af3451-6185-4439-8b8e-badb3de00624.png)
![shot389](https://user-images.githubusercontent.com/41944249/193471457-8c2b528f-1285-47ca-8c87-9fa164172fa4.png)
![shot388](https://user-images.githubusercontent.com/41944249/193471474-26926903-5120-45f0-ae46-558d1f8df153.png)

**Comment by VincentNLOBJ** [comment]
It must be addressed globally, cheers cheers for pointing this out!
