### ISSUE TITLE
more instances of poor english inconsistencies

### ISSUE THREAD

**Issue by ToddlerPichu** [NaomiMod/Rent-A-Hero-No1#118]
I am really sorry if this is already being taken care of, I just hoped to point it out in hopes it is not overlooked. I found another instance of the girl going from poor english to perfect english in the same scene depending on if suit is worn (feel free to close if its already known)
![shot397](https://user-images.githubusercontent.com/41944249/193473434-7ee9eeb7-42c6-42a6-a207-78153bd10744.png)
![shot398](https://user-images.githubusercontent.com/41944249/193473437-a626c574-7181-4437-b1b7-e64e65d98bbe.png)

**Comment by VincentNLOBJ** [comment]
The girl and business man should have poor english dialogues, do they have any quest?

**Comment by ToddlerPichu** [comment]
No quests that I am aware of, but I was pointing out that taking to her in suit her english is fine

**Comment by VincentNLOBJ** [comment]
It's funny how they overlooked this in XB prototype :)

**Comment by ToddlerPichu** [comment]
They overlooked a lot in the xbox prototype it seems... i would almost argue it is making our jobs harder not easier XD

**Comment by ToddlerPichu** [comment]
Finally complete and fixed NPCs that shouldnt have poor english mixed with text from others that should
