### ISSUE TITLE
A20_hard crash after work completion (redream)

### ISSUE THREAD

**Issue by ToddlerPichu** [NaomiMod/Rent-A-Hero-No1#123]
After completing Mrs.Tee's job to get her boys to stop fighting you receive her reward, exit the house and fight the Black Sheeps... after those events win or lose, next loading screen will hard crash you closing the emulator (Redream in this case)

However if using Demul (v0.7 111117 in this case) the game does not crash HOWEVER, there are some graphical oddities such as boxes around places text not showing up which previously worked (picture of example: before reward collected/gang fought on top... after on bottom)
![Untitled](https://user-images.githubusercontent.com/41944249/193479914-a16e92a7-349f-417c-ba5b-5064183a7d54.png)

I am attaching my save file if it is needed for testing... quest goals are completed, all that is needed is to exit the house, walk right to Mrs. Tee's, talk with her and proceed to collect the reward and fight the gang next scene win or lose and next time the game would load some area is where it bugs
[RENTA1___004.zip](https://github.com/NaomiMod/Rent-A-Hero-No1/files/9693752/RENTA1___004.zip)

**Comment by ToddlerPichu** [comment]
I will be halting testing for the moment now, as I do not want to save over my file through progressing on a different emulator or the JP version and have possible unforeseen consequences once I continue testing the translation project on my main emulator

**Comment by VincentNLOBJ** [comment]
Ok, definitely a critical bug!
Will investigate your save today

**Comment by VincentNLOBJ** [comment]
I cannot replicate the issue wiht Redream or Demul, will send you v0.13 later today.

**Comment by ToddlerPichu** [comment]
Wonderful, new revision does seem to have fixed it, thank you.
