### ISSUE TITLE
A22_Mieu's job description huge spaces

### ISSUE THREAD

**Issue by ToddlerPichu** [NaomiMod/Rent-A-Hero-No1#127]
In the job description huge spaces between some words, making 1 word cut into 2 lines of text
![shot412](https://user-images.githubusercontent.com/41944249/193654612-eb38d4a1-e74f-497b-8e3e-b8fcae4cadd4.png)
![shot413](https://user-images.githubusercontent.com/41944249/193654615-6ef5ea18-7cb0-42c1-95ab-a3c715d47f03.png)

**Comment by Guimli355** [comment]
I think it's the same job, but not the same description... I have some extra space between the !   !
![IMG_20221006_232634](https://user-images.githubusercontent.com/113843539/194427887-f8f6d9a7-4371-40d6-8f91-61d51a78ebeb.jpg)
