### ISSUE TITLE
B01_Bank 1.5 issue

### ISSUE THREAD

**Issue by ToddlerPichu** [NaomiMod/Rent-A-Hero-No1#13]
In Bank 1.5 talking to a teller brings up this menu calling it "CLIPPNOTES Bookstore" with a list of books, all with a price of 0 and unpurchaseable 
![shot35](https://user-images.githubusercontent.com/41944249/191756901-73b648f3-ce15-48f7-90d9-245d01838ecc.png)

**Comment by ToddlerPichu** [comment]
For reference, this is what you see entering Clippnotes Bookstore at this point in the game (of note, the books are purchasable and added to inventory here as they should be):
![shot36](https://user-images.githubusercontent.com/41944249/191757918-3be4a075-c5bc-4a4a-9e16-e40e21e8e9d0.png)

**Comment by VincentNLOBJ** [comment]
Critical bug, thanks for reporting!

If you find more errors like this, please upload your save here if possible, thanks.

**Comment by ToddlerPichu** [comment]
I can provide a save file at this point now if you'd like. This save file should be the closest save you can get to when it first occurs.
[RENTA1___002.zip](https://github.com/NaomiMod/Rent-A-Hero-No1/files/9629534/RENTA1___002.zip)

**Comment by incrediblemeltingmatt** [comment]
I have the same issue.  I think It's soft-locked me from progressing any further. Any tips on how to get out of it?

**Comment by VincentNLOBJ** [comment]
I'm investigating the issue and it's connected to wrong game function execution, present on Hero Name as well.
Thank you very much for reporting this, please suspend Beta Testing for the moment.

I'll fix critical bugs and send you back a new version once ready!

**Comment by VincentNLOBJ** [comment]
Thank you for the save file! 💯 

Basically it's a function mapping issue, all I had to do were to rewrite the original function ID order.
