### ISSUE TITLE
A16_Bud green vs Dr. Beaker in mail

### ISSUE THREAD

**Issue by Guimli355** [NaomiMod/Rent-A-Hero-No1#131]
After completing the dance gas mission, you receive a mail from Dr. Beaker. But it should be from Bud Green I think.
![IMG_20221003_230935](https://user-images.githubusercontent.com/113843539/193684103-f7be3245-32d5-42d0-9dc3-bd1674ec836c.jpg)

**Comment by VincentNLOBJ** [comment]
It's Bud Green, thanks for reporting!
