### ISSUE TITLE
OutTrigger vmu minigame

### ISSUE THREAD

**Issue by Guimli355** [NaomiMod/Rent-A-Hero-No1#132]
How do you play the Out Trigger mini game? After the title screen I see rent a Hiroko walking, then a bird coming, the one fell swoop and then the end. It seems that pressing button don't do anything... 

If it's not normal, I will try the Japanese version tomorrow.

**Comment by ToddlerPichu** [comment]
I am not sure myself how to play them or if they are even playable... any 3 of the mini games, in japanese or english, I load them up press A+B and i am convinced they are just a way to display what is basically a .gif on your VMU at the expensive of a 4th of its memory
