### ISSUE TITLE
A23_incomplete parentheses_text in parentheses

### ISSUE THREAD

**Issue by ToddlerPichu** [NaomiMod/Rent-A-Hero-No1#136]
The starting parentheses is missing on the ending message and the message is wrong at start... the "s" should probably be "(He" for the whole message to be " (He had his teeth knocked out and can't speak clearly.)"
For reference the JP version says
```
ゴホゴホ ･･･
まねらば ほら へれ しゃれ れ らり
( まえ 歯 が 折ら れ て しゃべれ ない )
```
![shot422](https://user-images.githubusercontent.com/41944249/193708402-88115bff-8437-463d-94e1-bebf888ad40d.png)

**Comment by VincentNLOBJ** [comment]
👍
