### ISSUE TITLE
A01_3_message after name creation

### ISSUE THREAD

**Issue by ToddlerPichu** [NaomiMod/Rent-A-Hero-No1#139]
Just after selecting your name and starting new game you get these messages before the game starts normal
![shot428](https://user-images.githubusercontent.com/41944249/193946053-07dfff38-07c9-47d6-aec6-ec521fd2b926.png)
![shot429](https://user-images.githubusercontent.com/41944249/193946056-26145b4b-97db-4d20-acf4-b5b734635d9a.png)
![shot430](https://user-images.githubusercontent.com/41944249/193946062-61ff98c6-bbfc-4288-a6bc-0df4d3cfd939.png)

**Comment by VincentNLOBJ** [comment]
Ouch, my bad I've used this to test last unmapped control codes, it's removed from v0.14
