### ISSUE TITLE
A01_3_to  be

### ISSUE THREAD

**Issue by madmatmax** [NaomiMod/Rent-A-Hero-No1#14]
It looks like there is 2 spaces between to  be

![B8C889D7-3C51-45B1-A25D-6CB7365439C5](https://user-images.githubusercontent.com/44887318/191782486-990a7e50-9cec-48a3-a329-7e17b90f63a8.jpeg)

**Comment by VincentNLOBJ** [comment]
Got it, thanks @madmatmax !
