### ISSUE TITLE
A02_Player's Home

### ISSUE THREAD

**Issue by ToddlerPichu** [NaomiMod/Rent-A-Hero-No1#144]
After selecting your hero's name your houses name changes to "[Hero Name]'s Home" when it should probably be "[First Name]'s Home" as that is what it is referred to as in some side quests. In the JP version does not have the issue with home's name changing and your home's name is always [Last Name]'s Home... but First name is more appropriate for English and is already referred to as such in some instances.
![shot443](https://user-images.githubusercontent.com/41944249/193950289-7b867669-094c-424b-9d3e-59d40d3db17a.png)

**Comment by VincentNLOBJ** [comment]
Changed to First Name, good one!
