### ISSUE TITLE
A24_formatting (may be because of " to " issue)

### ISSUE THREAD

**Issue by ToddlerPichu** [NaomiMod/Rent-A-Hero-No1#148]
Text spilling out of text box area... may not be a issue once " to " is fixed, but reporting on the off chance that is not the case
![shot452](https://user-images.githubusercontent.com/41944249/194002891-d77bcd0b-b2d4-4bd0-a2a5-267b641a237e.png)

**Comment by VincentNLOBJ** [comment]
Done!
