### ISSUE TITLE
A02_seca_manual_3_when you don

### ISSUE THREAD

**Issue by Guimli355** [NaomiMod/Rent-A-Hero-No1#16]
Maybe it's when you put instead of when you don.
![IMG_20220922_205841](https://user-images.githubusercontent.com/113843539/191833621-f09c69a9-e97f-4f74-93e6-82dd37502d40.jpg)

**Comment by ToddlerPichu** [comment]
This is correct.
Definition of Don:
verb, "to put on (an article of clothing)"

**Comment by Guimli355** [comment]
My bad, as a French, it's the first time I see this verb. I guess I will learn new things here.
