### ISSUE TITLE
A25_ending credits_armour_labour

### ISSUE THREAD

**Issue by ToddlerPichu** [NaomiMod/Rent-A-Hero-No1#180]
"Armour" is used once in ending credits subtitles where "armor" is used many times... "labour" is also used once going against the american localization of spelling and should be changed to "labor"
![shot537](https://user-images.githubusercontent.com/41944249/194483180-11f4da45-3418-4250-9d00-e91a894d4874.png)
![shot541](https://user-images.githubusercontent.com/41944249/194483210-27139819-aa67-4e22-bd46-b872f1090b5e.png)

**Comment by VincentNLOBJ** [comment]
Awesome! You did finish the game already?
