### ISSUE TITLE
A22_Narco warehouse Nomoruwa texture

### ISSUE THREAD

**Issue by Guimli355** [NaomiMod/Rent-A-Hero-No1#183]
The name Nomoruwa is remaining on the Narco warehouse door. I remember the inside of the warehouse was translated.
![IMG_20221007_221235](https://user-images.githubusercontent.com/113843539/194645703-30783f75-56fa-461e-9de3-fc0d0fadff74.jpg)

**Comment by VincentNLOBJ** [comment]
Done!
