### ISSUE TITLE
A24_s to ry

### ISSUE THREAD

**Issue by Guimli355** [NaomiMod/Rent-A-Hero-No1#184]
There is an issue of spaces in "story" 
![IMG_20221007_230804](https://user-images.githubusercontent.com/113843539/194652784-d67ea32b-409e-4333-bf55-d95754210035.jpg)

**Comment by ToddlerPichu** [comment]
The " to " issue is already known and currently only A14, A20 and A24 should have the issue. I believe Vincent will make sure to fix the remaining ones you'll find, so I believe you can hold off on reporting them unless we get different directions.

I do say though, I couldn't have asked for a better person to have as a partner for beta testing Guimli... not only have you stuck through to the end (or near to it so far), but youre also on real hardware and giving a nice confirmation on if things work or break. I really value your diligence having you catch the same bugs and different bugs from me playing and was only able to do my best work as beta tester thanks to you being here testing as well!

**Comment by Guimli355** [comment]
Ha that's why you didn't reported it! I thought it was strange you didn't find it😁. I will close it.
Thanks for your word. It's my first beta testing, it's fun to do.  RAH is a game I wanted to try for years. 
But I can't compete with you. Are you used to beta testing or are you in the translation team? You seems to know a lot.
![IMG_20221008_102909](https://user-images.githubusercontent.com/113843539/194698196-d7c9bfad-1a40-4a3f-aff7-de6e25afcd87.jpg)

**Comment by ToddlerPichu** [comment]
@Guimli355 I have past experiences with translating and localizing literature... and I play a lot of video games XD
but as for project RAH... I was not on the translation team, I only found out about the project in time to be a beta tester but I was passionate about the game so I joined
