### ISSUE TITLE
A01_3_house warming

### ISSUE THREAD

**Issue by cicadas-dc** [NaomiMod/Rent-A-Hero-No1#186]
i usually see this term written as a compound word - "housewarming," or sometimes "house-warming."
"house warming" isn't incorrect, just kind of uncommon.
![A01_3-housewarming-Screenshot 2022-11-12 10-23-20-50](https://user-images.githubusercontent.com/114700661/201494788-659a6a1d-5f95-4c35-bb6a-6d592478fe17.png)

**Comment by ToddlerPichu** [comment]
You are correct and all instances of `house warming` have been changed to `housewarming` on my side now, thank you very much.
