### ISSUE TITLE
A01_3_missing punctuation

### ISSUE THREAD

**Issue by cicadas-dc** [NaomiMod/Rent-A-Hero-No1#187]
when first speaking to the computer businessman at the very beginning, there is missing punctuation between the player's name and the following sentence.
it should probably be:

[player],
do you have a computer?

or

[player]...
Do you have a computer?

![A01_3-computer-internet-Screenshot 2022-11-12 10-32-58-50](https://user-images.githubusercontent.com/114700661/201494859-6f002fd0-d4e1-4354-a07f-229104358128.png)

(the yen sign in my character's name is unrelated - it's there on purpose to fill out the maximum player name length.)

**Comment by ToddlerPichu** [comment]
Thank you, it has been changed to:
```
[FIRST_NAME],
do you have a computer？
Do you use the internet?
