### ISSUE TITLE
C01_item not readable

### ISSUE THREAD

**Issue by Guimli355** [NaomiMod/Rent-A-Hero-No1#19]
I've found an item in the room but as it's highlighted in green it's unreadable on crt. Happened one other time in blue.
![IMG_20220922_211508](https://user-images.githubusercontent.com/113843539/191834796-e3de71e0-a60e-48af-9026-9f95fefd97c0.jpg)

**Comment by Guimli355** [comment]
It's not at the same place, but no issue of text unreadable in the Japanese version, when I find an item. The text is green but not highlighted.
![IMG_20220923_223246](https://user-images.githubusercontent.com/113843539/192052371-a280d825-3d21-4124-9447-298456793a79.jpg)

**Comment by VincentNLOBJ** [comment]
This issue is caused by a write instruction in"items" variable:
[ENERGY_DRINK]を

Because the variable is written as the first word, by shifting the "items" variable to another position breaks things up.
I got an idea as a workaround, let's see how this goes!

**Comment by VincentNLOBJ** [comment]
![immagine](https://user-images.githubusercontent.com/71412899/192139105-a4451c43-6809-4460-89df-810723a34ec0.png)

**Comment by Guimli355** [comment]
Bravo! Do you think the solution you find will now work for all items or should we find all the game hidden items for you to fixe them one by one?

**Comment by VincentNLOBJ** [comment]
All items should dispaly as intended!
