### ISSUE TITLE
A04_DoReMe/DoReMi inconsistency in textures

### ISSUE THREAD

**Issue by cicadas-dc** [NaomiMod/Rent-A-Hero-No1#194]
the name of the pizza restaurant in Driveby City is written inconsistently as DoReMe several times on the outside of the building and as DoReMi on the mat inside.
![A04_DoReMe-pizza2-Screenshot 2022-11-16 18-34-26-c](https://user-images.githubusercontent.com/114700661/202361755-30118281-eca2-4d7f-84a9-cde1789235e5.png)
![A04_DoReMe-pizza1-Screenshot 2022-11-15 19-15-30-50](https://user-images.githubusercontent.com/114700661/202361730-dfc65370-e67b-4c29-a5a6-49ac33e59956.png)

**Comment by VincentNLOBJ** [comment]
Nice catch! 👍

**Comment by ToddlerPichu** [comment]
@VincentNLOBJ Actually let me take a look at the games text before making a decision on which texture needs to be changed to "Mi" or "Me"... i might know some inconsistences that will dictate which one will be best to change (either way, i think i found some text work i will need to do on this issue in conjunction with your side with textures)

**Comment by ToddlerPichu** [comment]
As Vincent said though, nice catch Cicadas 👍

**Comment by VincentNLOBJ** [comment]
Actually it's my bad here, due to how Do Re Mi (notes) are pronounced, I only focused on `Le` --> `Re`.

**Comment by ToddlerPichu** [comment]
@VincentNLOBJ No worries... I just fixed all instances of `DoReMe` to -> `DoReMi`, all I need on your side is to handle the textures

**Comment by VincentNLOBJ** [comment]
![immagine](https://user-images.githubusercontent.com/71412899/204568102-f523aa6c-2697-444e-a7e7-6a50595b87e3.png)

**Comment by VincentNLOBJ** [comment]
![immagine](https://user-images.githubusercontent.com/71412899/204571969-07965ab7-c7f5-42aa-aa54-caf988ff286d.png)
