### ISSUE TITLE
A04_ELEVETER texture

### ISSUE THREAD

**Issue by cicadas-dc** [NaomiMod/Rent-A-Hero-No1#197]
in SECA headquarters B2, the floor in front of the elevator reads "ELEVETER" -

![A04_ELEVETER-Screenshot 2022-11-16 18-30-18](https://user-images.githubusercontent.com/114700661/202544356-ba13be02-12a2-43cd-af5a-969bd0c8ed54.png)

the unpatched Japanese version has the same texture, so changing it or not changing it might be a matter of taste.

**Comment by VincentNLOBJ** [comment]
![immagine](https://user-images.githubusercontent.com/71412899/204365067-9a0029ed-e58f-4fb1-9d39-30bf1ee29e8e.png)
