### ISSUE TITLE
Opening_common_people

### ISSUE THREAD

**Issue by chrisasma103** [NaomiMod/Rent-A-Hero-No1#199]
I don't know if this is the kind of issue that's allowing, but I though that this seemed like an error in the opening movie. It says "Even common people, can become immortal." I don't believe the comma is correct here.
![Rent A Hero No 1-221115-123056](https://user-images.githubusercontent.com/41581802/202867772-7096f44a-5579-45aa-9dcd-2157a23063bd.png)

**Comment by ToddlerPichu** [comment]
The comma does not appear to be correct, no... thank you for the report.

**Comment by VincentNLOBJ** [comment]
> The comma does not appear to be correct, no... thank you for the report.
Just in case it weren't tracked before, this line is stored in Chunk 97_Opening_Subs, text 8

**Comment by ToddlerPichu** [comment]
Thank you Vincent, got it... I uh, just forgot to close the report after fixing it XD
