### ISSUE TITLE
C01_no music

### ISSUE THREAD

**Issue by Guimli355** [NaomiMod/Rent-A-Hero-No1#20]
When I'm inside a house there is no music only traffic sounds. It seems I can't attached video, but I can send it by email.

**Comment by Guimli355** [comment]
I have the same issue with the Japanese version. In the houses, I only hear the background sound from the road and no music.
@ToddlerPichu You play with an emulator? Do you have the same issue?

**Comment by VincentNLOBJ** [comment]
The lack of music seems intentional.
It's consistent in original JP game as well. If you won't find any changes in emulators, please feel free to close this issue.

**Comment by Guimli355** [comment]
You're right I checked on YouTube playthrough it's the same, only background sound in the houses. I close the issue.

**Comment by ToddlerPichu** [comment]
All is confirmed on my side as well, as Guimli said issue can be closed. Thank you
