### ISSUE TITLE
A06_[Hero] hello

### ISSUE THREAD

**Issue by cicadas-dc** [NaomiMod/Rent-A-Hero-No1#207]
when first accepting the mission from him, the mayor of Clean Bay greets the hero with
> Oh! [Hero] hello.

this might need a comma:
> Oh! [Hero], hello.

![A06_Herohello-Screenshot 2022-11-18 12-12-41-50c](https://user-images.githubusercontent.com/114700661/202934469-727e561f-fc98-4ff7-94ea-bd656aacc7dd.png)

**Comment by ToddlerPichu** [comment]
Good catch, fixed
