### ISSUE TITLE
A06_suspicious looking

### ISSUE THREAD

**Issue by cicadas-dc** [NaomiMod/Rent-A-Hero-No1#208]
when you wear the hero suit, the guard in front if the NARCO Lab building says

> You're a suspicious looking character.
> If you don't leave, I'll have to teach you a lesson.

according to the following site, this term is a "compound adjective" and should be hyphenated as "**suspicious-looking**."

> You're a suspicious-looking character.

https://www.grammarbook.com/punctuation/hyphens.asp
![A06_suspicious-Screenshot 2022-11-30 13-21-59-50c](https://user-images.githubusercontent.com/114700661/204924094-390ecf75-7262-4df5-a7dd-1e4fc1fc4cba.png)

**Comment by ToddlerPichu** [comment]
Seems you are right, thank you for the report and the English lesson... I never would have caught that on my own in 100 years. Revised to `suspicious-looking`
