### ISSUE TITLE
A06_fighting salesmen

### ISSUE THREAD

**Issue by cicadas-dc** [NaomiMod/Rent-A-Hero-No1#209]
when Ultrasalaryman first introduces himself, he says:

> Hey [Hero], you're doing well.
> Keep up the good work!
> I'm the fighting salesmen!

since he's only talking about himself, this is likely meant to be the singular "salesman"

> Keep up the good work!
> I'm the fighting **salesman**!

![A06_salesmen-Screenshot 2022-11-30 13-49-46-50c](https://user-images.githubusercontent.com/114700661/204924836-75b71fb0-ef83-4e38-aad4-739aba3e2d99.png)

**Comment by ToddlerPichu** [comment]
Good catch, fixed
