### ISSUE TITLE
A06_You got a fight

### ISSUE THREAD

**Issue by cicadas-dc** [NaomiMod/Rent-A-Hero-No1#210]
in Ultrasalaryman's self-introduction:

> You got a fight! For your right!

"got a" should probably be "gotta" - especially if it's meant to evoke the Beastie Boys song "(You Gotta) Fight for Your Right"

> You **gotta** fight! For your right!

![A06_gotafight-Screenshot 2022-11-30 13-51-39-50c](https://user-images.githubusercontent.com/114700661/204925342-12e29510-b4e4-4f42-8a7d-ba7e897fdd40.png)

**Comment by ToddlerPichu** [comment]
Lol, goofy song. It does appear to be a reference and slang term `gotta` is appropriate here, revised `got a` to `gotta`, thank you
