### ISSUE TITLE
A06_just like you Rent-A-Hero

### ISSUE THREAD

**Issue by cicadas-dc** [NaomiMod/Rent-A-Hero-No1#211]
Ultrasalaryman's line

> I'm just like you Rent-A-Hero!

might need a comma: 

> I'm just like you, Rent-A-Hero!

![A06_likeyourentahero-Screenshot 2022-11-30 13-58-30-50c](https://user-images.githubusercontent.com/114700661/204925778-9e8ef6ef-e1d5-4549-b143-cddd0932b45a.png)

**Comment by ToddlerPichu** [comment]
Comma added, thank you for the report
