### ISSUE TITLE
A06_before It's too late

### ISSUE THREAD

**Issue by cicadas-dc** [NaomiMod/Rent-A-Hero-No1#212]
in a line from the mayor of Clean Bay, the word "It's" appears to be mistakenly capitalized after the line break:

> Please save this young boy before
> It's too late! Hurry, heroes!

should likely be revised to:

> Please save this young boy before
> **it's** too late! Hurry, heroes!

![A06_Its-Screenshot 2022-11-30 14-01-47-50c](https://user-images.githubusercontent.com/114700661/204926275-a76515d0-15b9-44f7-bd84-f8ccc3c64c21.png)

**Comment by ToddlerPichu** [comment]
Very nice catch, I had thought I eliminated all of these capital on line break issues. Line has been fixed now, thank you
