### ISSUE TITLE
D01_Go to residence

### ISSUE THREAD

**Issue by cicadas-dc** [NaomiMod/Rent-A-Hero-No1#213]
in the mission briefing for "Shopping Request," when the client is from Coco-nuts Apt., Mieu says

> Go to [client] residence.

![D01_Gotoresidence-Screenshot 2022-11-30 15-25-48-50](https://user-images.githubusercontent.com/114700661/204927942-6f1ff66a-f0f8-4c79-8632-1c84c06ea154.png)

in contrast, when the client is from Hangover Park, Mieu says 

> Go to **the** [client] residence.

![D01_Gotoresidence-Screenshot 2022-11-30 15-20-14-50](https://user-images.githubusercontent.com/114700661/204927557-39175221-1b0b-4a2a-865c-3a02b3a7b76e.png)

if possible, she should likely say "the" in both variants for consistency.

here's a save file from right before accepting the mission:
[D01_Gotoresidence-RENTA1___001.02.vms.zip](https://github.com/NaomiMod/Rent-A-Hero-No1/files/10127960/D01_Gotoresidence-RENTA1___001.02.vms.zip)

**Comment by ToddlerPichu** [comment]
All shopping request text has been revised for this issue where needed, thank you
