### ISSUE TITLE
A06_Now Loading

### ISSUE THREAD

**Issue by cicadas-dc** [NaomiMod/Rent-A-Hero-No1#214]
strange capitalization on Meiu's loading message after accepting a new job.

> Now Loading data...

should probably be 

> Now **loading** data...

![A06-Loading-Screenshot 2022-11-30 15-20-00-50c](https://user-images.githubusercontent.com/114700661/204932880-0aeef330-8ac4-4a48-8f10-ffc6546c985d.png)

**Comment by ToddlerPichu** [comment]
There are a few places this seems to be present, fixed 2 instances in `20_Work Menu.bin` and 1 instance in `01_Game Messages.bin`... should you find this same mistake any other places not related to the work menu or debug menu, please report it. Same for if there are any instances of "Now Saving", though I do not recall any. Thank you for report
