### ISSUE TITLE
D01_help for shopping

### ISSUE THREAD

**Issue by cicadas-dc** [NaomiMod/Rent-A-Hero-No1#215]
when accepting the mission "Shopping Request," depending on the client, Mieu can say

> [Client], a resident of [location], is requesting help for shopping.

or

> [Client], who lives in [location], is requesting help for shopping.

"help for shopping" sounds a bit unnatural. it might need to be revised to "help with shopping"

> [Client], a resident of [location], is requesting help **with** shopping.

![D01_helpforshopping-Screenshot 2022-11-30 15-23-40-50](https://user-images.githubusercontent.com/114700661/204933328-4029c957-c972-4c17-b682-ad89a835ce1f.png)

![D01_Gotoresidence-Screenshot 2022-11-30 15-25-48-50](https://user-images.githubusercontent.com/114700661/204933752-6ce4e413-1cdc-497d-a37a-1bf2c4a593f8.png)

**Comment by ToddlerPichu** [comment]
6 instances of `help for shopping` have been changed to `help with shopping`, thank you
