### ISSUE TITLE
B01_Train station selection

### ISSUE THREAD

**Issue by Guimli355** [NaomiMod/Rent-A-Hero-No1#22]
When at the train station, the selected station is not marked. I can only go left, as if I press the right/up/down button there is no sound. After about ten left press, the clean bay become purple and it's impossible to change the station.
![IMG_20220922_224309](https://user-images.githubusercontent.com/113843539/191850871-7ceaca44-04b9-47a0-bb62-c0e46f79b0ad.jpg)
![IMG_20220922_224333](https://user-images.githubusercontent.com/113843539/191850890-7e9b8a91-22c3-4763-b278-2c5aa94835b9.jpg)

**Comment by ToddlerPichu** [comment]
To expand on this... I seem to have the same issue, but there is more to it:
Each location seems to have a different amount you can press before Clean bay is highlighted and no directions can be pressed anymore (Hangover Park Station is 37, Now Dork Station 9, etc)... pressing right 8 times and selecting in Hangover Park Station brings you to Now Dork Station, **in New Dork Station pressing right once and selecting will softlock you on a blackscreen**
![shot44](https://user-images.githubusercontent.com/41944249/191874026-debcaa15-c284-4712-ac5d-c0b778f10e6e.png)

**Comment by VincentNLOBJ** [comment]
Emulation results are abit inconsistent on this.
@Guimli355 Can you try using the original JAP game with the same save, to report if it behaves in the same way on HW?

**Comment by Guimli355** [comment]
On the Japanese version, with the same save, I have no train issue. I can select the station normally. The selected station become violet. But I can only choose Kouja and otoori. With the patched version I was able to go to Dahmane (the big city with a D statue).
![IMG_20220923_221520](https://user-images.githubusercontent.com/113843539/192051150-27c01b62-9900-4f4e-aa0b-60876ce4b866.jpg)

**Comment by VincentNLOBJ** [comment]
Got it thanks guys! I'll analyze that specific code chunk.

**Comment by VincentNLOBJ** [comment]
![immagine](https://user-images.githubusercontent.com/71412899/192094508-4b9ba8e2-a98b-4b47-bac1-a0ca57ecf9c7.png)
This issue is created by a number of wrong pointers during text rebuild.
I'm on it!

**Comment by VincentNLOBJ** [comment]
Done! 👍
