### ISSUE TITLE
A06_Combat Armors

### ISSUE THREAD

**Issue by cicadas-dc** [NaomiMod/Rent-A-Hero-No1#221]
in Mieu's "SECA Manual 6" mail:

> Aside from new Super Energy Combat Armors,

as far as i'm aware, the plural form of "armor" is always "armor."

> Aside from new Super Energy Combat **Armor**,

i understand that this sentence is referring to multiple suits of Rent-A-Hero armor, but i can't immediately think of a revision that would keep that nuance.
![A06_Combat-Armors-Screenshot 2022-12-06 13-07-13-50](https://user-images.githubusercontent.com/114700661/206315127-27b70a1e-df2b-4f18-99fe-41a37a4b1d8b.png)

**Comment by ToddlerPichu** [comment]
All instances of `armors` should be `armor` now... please disregard the instances you will find in late game, thank you for the report
