### ISSUE TITLE
A06_About Driveby City mail

### ISSUE THREAD

**Issue by cicadas-dc** [NaomiMod/Rent-A-Hero-No1#223]
in Mieu's "About Driveby City" mail, this is a bit of a run-on sentence.

> Your work will often overlap with the police, so you'll be taken care of by them, please rest assured that you are in good hands with them!

i suggest:

> Your work will often overlap with the police, so you'll be taken care of by them. Please rest assured that you are in good hands with them!

![A06_About-Driveby-City-Screenshot 2022-12-06 13-22-49-50](https://user-images.githubusercontent.com/114700661/206319010-df64843d-683f-42be-9f59-57163aba6cd4.png)

**Comment by ToddlerPichu** [comment]
Revised `them, please` to `them. Please` as suggested... thank you
