### ISSUE TITLE
D01_over eat

### ISSUE THREAD

**Issue by cicadas-dc** [NaomiMod/Rent-A-Hero-No1#225]
at the Penguin Restaurant -

> Please be careful not to over eat, though.

this is a compound word and should be spelled "overeat"

> Please be careful not to **overeat**, though.

![D01-over-eat-Screenshot 2022-12-06 13-48-42-50](https://user-images.githubusercontent.com/114700661/206321332-326ee2d6-e3bc-4237-8968-e5b87e01ba08.png)

**Comment by ToddlerPichu** [comment]
Revised `over eat` to `overeat`... thank you for the report
