### ISSUE TITLE
D01_far away

### ISSUE THREAD

**Issue by cicadas-dc** [NaomiMod/Rent-A-Hero-No1#226]
at the Penguin Restaurant -

> I came here from a far away place to start a restaurant.

this is a compound word and is more commonly spelled as "faraway" or "far-away"

> I came here from a **faraway** place to start a restaurant.

![D01-far-away-Screenshot 2022-12-06 14-02-22-50](https://user-images.githubusercontent.com/114700661/206321468-c4e0c1a8-393b-4d57-b4af-1c2cf4202442.png)

**Comment by ToddlerPichu** [comment]
When talking about adjectives "faraway" would be used to modify a noun... and "far away" is still used, but in a phrase like adverb. I do not believe they are interchangeable, so this does seem to be a full error and less of what is a more common spelling if i am not mistaken.
Revised `far away place` to `faraway place`... thank you for the report
