### ISSUE TITLE
B01_GIGO arcade text

### ISSUE THREAD

**Issue by ToddlerPichu** [NaomiMod/Rent-A-Hero-No1#23]
Talking to the money changer machine in GIGO Arcade you get unreadable/glitchy text... you receive a HiP-PP from doing so
![shot39](https://user-images.githubusercontent.com/41944249/191869451-0bdc5ec9-cd57-4584-be28-88d9c49639c6.png)

**Comment by VincentNLOBJ** [comment]
![immagine](https://user-images.githubusercontent.com/71412899/192142522-4a82e9e6-b305-4f35-aa43-f6696e06e39b.png)
Done!
