### ISSUE TITLE
A08_out for awhile

### ISSUE THREAD

**Issue by cicadas-dc** [NaomiMod/Rent-A-Hero-No1#234]
same minor grammar error as "A08_awhile vs a while" but after passing the "Clean Up Driveby City" mission instead of failing it.
a guard outside the bank says:

> I must have been out for awhile.

revised:

> I must have been out for **a while**.

![A08_out-for-awhile-Screenshot 2023-01-16 14-07-24-c](https://user-images.githubusercontent.com/114700661/213942272-a7e23f96-07f5-43e6-9f01-cc7d2e046c03.png)

**Comment by ToddlerPichu** [comment]
Fixed most if not all `awhile vs a while` instances with the report of #230, this one included... thank you for the report
