### ISSUE TITLE
A07_body guard (quotation marks)

### ISSUE THREAD

**Issue by cicadas-dc** [NaomiMod/Rent-A-Hero-No1#235]
in the invitation in the doghouse, the quotation marks close before the end of the letter.

> The invitation reads,
> "Thank you for accepting the job of being my body guard".
> Please be in your hero outfit when presenting yourself at the Narco building.

the quotation marks should be at the end of the second message instead of at the end of the first one:

> The invitation reads,
> "Thank you for accepting the job of being my body guard.
> Please be in your hero outfit when presenting yourself at the Narco building."

additionally, "bodyguard" in this context should be a compound word:

> The invitation reads,
> "Thank you for accepting the job of being my **bodyguard**.
> Please be in your hero outfit when presenting yourself at the Narco building."

![A07_body-guard-Screenshot 2023-01-16 16-30-36-c](https://user-images.githubusercontent.com/114700661/213942446-0bc033eb-2c5f-4302-87df-ec0385930497.png)
![A07_body-guard-Screenshot 2023-01-16 16-30-45-c](https://user-images.githubusercontent.com/114700661/213942483-e5ef522d-b96b-44b4-9b0d-8382b97fac40.png)

**Comment by ToddlerPichu** [comment]
Been fixed on my side for awhile... thank you for the report
