### ISSUE TITLE
Memory Card has not been initialized

### ISSUE THREAD

**Issue by cicadas-dc** [NaomiMod/Rent-A-Hero-No1#237]
i got the following message when starting the game with a VMU with very low battery (with an exclamation mark lit up in the corner of the vmu screen):

> "Memory Card in Port _X_ Socket _#_
> has not been initialized."

this itself is fine; however, the message lingers after first the button press and stays up even when "Please select a Memory Card" would normally come up. is this the intended behavior?

i booted the japanese version to check what it does in this situation, but by the time i figured out the issue was being caused by VMU batteries, the batteries had drained completely and the message had stopped coming up.

suggested solution: compare the scripts of the japanese version and the english translation to check the control codes in this message.

it may be possible to force the message in an emulator by editing memory addresses.

in the following screenshots, the vmu in Port D Socket 1 is the one with very low battery. the second screenshot shows that the message lingers even while being able to move the cursor and select a vmu.
![initialized-Screenshot 2022-11-15 15-12-47-c](https://user-images.githubusercontent.com/114700661/213944093-2afd8f8c-d936-44e0-be99-dabbcbcce72b.png)
![initialized-Screenshot 2022-11-15 15-12-53-c](https://user-images.githubusercontent.com/114700661/213944096-0c73d23f-da4c-42fe-a962-8891dfc11e6a.png)

if this is intended behavior, please feel free to close this issue. thank you for checking.

**Comment by VincentNLOBJ** [comment]
My DC controller + VMU without batteries, didn't show any messages. Does this happen only with low battery?

**Comment by VincentNLOBJ** [comment]
Will re-open this in case of other reports.
