### ISSUE TITLE
Fanmail New Controls Bug

### ISSUE THREAD

**Issue by VincentNLOBJ** [NaomiMod/Rent-A-Hero-No1#238]
Screen fadeout timer is not triggered by pressing L/R/Analog stick.

**Comment by ToddlerPichu** [comment]
L and R work fine actually, since they are naturally part of the buttons the game checks for... it is just the Analog stick we implemented for scrolling that does not reset the fadeout timer

**Comment by VincentNLOBJ** [comment]
Fixed!
