### ISSUE TITLE
B01_Post Box Text

### ISSUE THREAD

**Issue by ToddlerPichu** [NaomiMod/Rent-A-Hero-No1#24]
It is possible this issue comes up sooner, but I ran into it now. Talking to the post box seems to be the same error as I reported in #23 (unreadable/glitchy text)... you still receive a CELLmate Batt. C from doing so however, as intended
![shot40](https://user-images.githubusercontent.com/41944249/191870688-71736e49-615d-4cde-9d8a-1dc9383866e2.png)

**Comment by VincentNLOBJ** [comment]
![immagine](https://user-images.githubusercontent.com/71412899/192142467-1c59a901-301e-4c8a-b289-051f77329277.png)
Fixed, thank you for reporting! 👍
