### ISSUE TITLE
A04 Seca headquarters Lift text still in Japanese.

### ISSUE THREAD

**Issue by incrediblemeltingmatt** [NaomiMod/Rent-A-Hero-No1#26]
![IMG_4946](https://user-images.githubusercontent.com/113768306/191951257-26297c1a-e98a-4996-bd66-50ab75156e01.jpg)

**Comment by VincentNLOBJ** [comment]
Do you have any save available for this specific point?
Thank you!

**Comment by VincentNLOBJ** [comment]
The problem seems also connected to data pointers.

@Guimli355 @ToddlerPichu if have a save near any other elevator please let me know, thanks!

**Comment by Guimli355** [comment]
I don't have any save near an elevator. I tried today to go to this elevator but I couldn't because the train wouldn't let me go to driveby city.

**Comment by ToddlerPichu** [comment]
@VincentNLOBJ  Here is a save in the hotel... directly to a elevator in lobby
[RENTA1___004.zip](https://github.com/NaomiMod/Rent-A-Hero-No1/files/9639818/RENTA1___004.zip)

**Comment by VincentNLOBJ** [comment]
Got it thanks!
I'm looking into the issue right now.

**Comment by VincentNLOBJ** [comment]
![immagine](https://user-images.githubusercontent.com/71412899/192134790-b57a82b4-5700-4452-bed6-2c8c02ec2e28.png)
Cannot test others, but they should work as well.
