### ISSUE TITLE
A04_Hero's Name

### ISSUE THREAD

**Issue by ToddlerPichu** [NaomiMod/Rent-A-Hero-No1#35]
When talking to the bank manager (and possibly others) you are referred to as your first name instead of your hero name... this is not the case in the JP version as shown in the 2nd picture attached
![shot58](https://user-images.githubusercontent.com/41944249/192324141-c99a0e63-8d28-486f-9bba-2cb1fac3ff50.png)
![shot59](https://user-images.githubusercontent.com/41944249/192324439-5a727cb7-6e1b-46cd-8765-94497455553c.png)

**Comment by VincentNLOBJ** [comment]
Done!

**Comment by VincentNLOBJ** [comment]
Upon further inspection, there were a number of instances (50-60) that had First Name instead of Hero Name.
I've adjusted them all according to JP scritpt.
