### ISSUE TITLE
A01_ Hero Music Video Text_Henshin_Armour

### ISSUE THREAD

**Issue by ToddlerPichu** [NaomiMod/Rent-A-Hero-No1#36]
In the the music video at the start of the game after knocking out your dad, one of the scenes contains a use of "armour" and a use of "henshin"
![shot51](https://user-images.githubusercontent.com/41944249/192327689-f8e3742c-5528-4d43-9269-8b820963ef28.png)

**Comment by VincentNLOBJ** [comment]
![immagine](https://user-images.githubusercontent.com/71412899/192364312-58cf88c1-724e-4a4d-87bb-baee46150728.png)
