### ISSUE TITLE
A04_The Hip PP tragedy

### ISSUE THREAD

**Issue by Guimli355** [NaomiMod/Rent-A-Hero-No1#37]
There 2 things in this email:
AtMOic instead of atomic
Sadly, is written two times

And I guess, that the name is Onics instead of Sonic is wanted?

![IMG_20220926_230807](https://user-images.githubusercontent.com/113843539/192382145-bb1d04f7-ce18-415f-8e78-df93d56d49f9.jpg)
![IMG_20220926_230849](https://user-images.githubusercontent.com/113843539/192382175-0e2a7f4f-e74c-4cd8-a674-a5fc603d968f.jpg)

**Comment by ToddlerPichu** [comment]
and a use of double Sadly as seen in last picture "Sadly, Sadly, due to a major accident"

**Comment by VincentNLOBJ** [comment]
Fixed! Thank you @ToddlerPichu !
