### ISSUE TITLE
A04_Shark's loan textures

### ISSUE THREAD

**Issue by Guimli355** [NaomiMod/Rent-A-Hero-No1#38]
You (and your team) did a huge work for changing textures. For me this is not a real issue, as I guess it's difficult to change textures.

The door of sharks loan have caessen loan written (I guess it's the original name). Inside, the windows have Caessen loan written on them, and the mirror/transparence effect is no done correctly. The simmetry/rotation issue is not the same on all windows, if I remember correctly. I can check the jap version  tomorrow. Sorry for the pictures quality.

![IMG_20220926_222904](https://user-images.githubusercontent.com/113843539/192383360-73c63495-0150-4cc1-a692-33a52dfde218.jpg)
![IMG_20220926_222830](https://user-images.githubusercontent.com/113843539/192383433-93afa6a3-4e99-4ece-9776-c3e3c7a25093.jpg)

**Comment by ToddlerPichu** [comment]
That last picture is accurate to the JP game... that 1 window texture is flipped so it is a nonissue here. However the textures saying Caessen Loan are untranslated and from their original JP version, good catch.

**Comment by VincentNLOBJ** [comment]
Nice find @Guimli355 !

**Comment by VincentNLOBJ** [comment]
![immagine](https://user-images.githubusercontent.com/71412899/193416785-7b1d121d-79b2-48b1-a5d6-863d51db2e06.png)
![immagine](https://user-images.githubusercontent.com/71412899/193416828-165ebc87-9f53-4c99-88c2-6099c08fc594.png)

**Comment by VincentNLOBJ** [comment]
Reopening this as technical, 1  texture on the wall is V-Mirrored.

**Comment by VincentNLOBJ** [comment]
In order to do this fix, 3D model format used by MODELL_ALL.bin needs to be reversed.
The same does apply for the Cat wrong texture since they are both stored in the same file.

**Comment by Guimli355** [comment]
Is it worth the pain/work to do it? I can't imagine the work it represents.

**Comment by VincentNLOBJ** [comment]
![immagine](https://user-images.githubusercontent.com/71412899/193901556-bca0d799-44e0-419d-82a4-83a6c660794c.png)
