### ISSUE TITLE
A04_CopyCat Publishing_untranslated texture

### ISSUE THREAD

**Issue by ToddlerPichu** [NaomiMod/Rent-A-Hero-No1#39]
In mail "About Driveby City"  the publishing company referred to as CopyUs in game is referred to as CopyCat in mail.
The texture on the outside of the building is also untranslated as Akarii (2nd picture example of both the naming difference between mail and game for company, along with it being a picture of the untranslated texture) 
![shot63](https://user-images.githubusercontent.com/41944249/192412112-7e3c370d-9eff-4b7e-b9e5-691e03053f83.png)
![shot66](https://user-images.githubusercontent.com/41944249/192411734-355c5c6b-9a24-4cd8-8832-e187733b7976.png)

**Comment by VincentNLOBJ** [comment]
Fixed mail name, leaving this open for GFX task.

**Comment by VincentNLOBJ** [comment]
![immagine](https://user-images.githubusercontent.com/71412899/193423567-7227e094-dabf-470b-a1ea-81ee2592aca5.png)
