### ISSUE TITLE
A01_3_middle...

### ISSUE THREAD

**Issue by Guimli355** [NaomiMod/Rent-A-Hero-No1#4]
Missing email text after middle.
![IMG_20220921_225412](https://user-images.githubusercontent.com/113843539/191616049-ff9a628a-77d2-4ac3-ae55-9faa0f9108af.jpg)

**Comment by VincentNLOBJ** [comment]
Changed to -->

```
When pressed, the menu will open
but only outside of battle when
you are not moving.
```
