### ISSUE TITLE
A04_poor english 

### ISSUE THREAD

**Issue by ToddlerPichu** [NaomiMod/Rent-A-Hero-No1#43]
In Bling Bling Hotel 1 npc explicitly states they only understand a little english, but the 2 npcs by the piano speak in poor english with no indication of only understanding a little english... is this intentional or a issue? 

Picture for reference that is without issue:
![shot77](https://user-images.githubusercontent.com/41944249/192446891-7e3e7ee3-df06-4ddf-9b55-d58192d537e6.png)
Possible issues in these 2 NPCs, if unintentional:
![shot75](https://user-images.githubusercontent.com/41944249/192447303-df6fb54b-07bf-4a8b-98cc-1917c2d7d679.png)
![shot76](https://user-images.githubusercontent.com/41944249/192447312-c74da370-5f7e-4a42-8a66-b4547631caf0.png)

**Comment by VincentNLOBJ** [comment]
I confirm it's intentional and the same in JP version!
