### ISSUE TITLE
D01_Shopping Request Work bugged

### ISSUE THREAD

**Issue by ToddlerPichu** [NaomiMod/Rent-A-Hero-No1#44]
Since this work is random on who you will work for, I have tested a few and the issue is present for all... when getting to clients requests, the item name on the list of what you are supposed to buy never appears, leaving this unable to be completed correctly.
A save file can be provided both before accepting the work... or after accepting the work (Mrs. Tee specifically) on request.
Here are examples where the item is supposed to appear but instead its only the text unrelated:
![shot91](https://user-images.githubusercontent.com/41944249/192513620-5efc7b83-5884-4f2a-b5c2-d87d60c111e3.png)
![shot83](https://user-images.githubusercontent.com/41944249/192513068-0eea3d24-5c2f-4c19-a154-20ecea6e1237.png)
![shot88](https://user-images.githubusercontent.com/41944249/192513085-132de73c-0163-4393-b1c9-8961c00ac252.png)
![shot82](https://user-images.githubusercontent.com/41944249/192512753-4c4ae933-3e4a-4564-a26e-e102cbd9f285.png)
(Side note and may be out of the scope of focus for the project... but what I believe to be Mrs. Tee's cat's texture is really messed up in the original JP version and consequentially the EN translation project. Is this fixable?)

**Comment by VincentNLOBJ** [comment]
![immagine](https://user-images.githubusercontent.com/71412899/192592245-6cb5baef-b608-477d-a371-211f9f080fe2.png)
Referring to the first pic:

As you can see in the original game text, there's no item being displayed, just an "と".
Can you confirm what happens in the JAP version?

He asks you to buy some groceries at Marshmallow fields, If you know which items are required to pass this work, I can simply write them and rephrase text.

**Comment by VincentNLOBJ** [comment]
Regarding Cat texture please open a separate Issue, I'm fairly certain it refers to a wrong texture ID.
The model needs to be found and patched. I'll pass it to our 3D modeller 👍

**Comment by ToddlerPichu** [comment]
The reason your scenario viewer is only showing と is because much like which client asks for you, the list of what you need to buy is not predetermined... but I verified before opening issue that it does function in the JP version.
![shot123](https://user-images.githubusercontent.com/41944249/192671033-d0ec0d23-ceca-49f2-b293-141d573eb82f.png)
![shot123](https://user-images.githubusercontent.com/41944249/192671170-cc980c2e-53be-4eca-af01-a80001476517.png)

**Comment by ToddlerPichu** [comment]
And here is the save from after accepting the job for Mrs. Tee... all that is needed is to go to her house as hero to start the list
[RENTA1___004.zip](https://github.com/NaomiMod/Rent-A-Hero-No1/files/9661055/RENTA1___004.zip)

**Comment by VincentNLOBJ** [comment]
![shot123](https://i.imgur.com/6AB1MAy.gif)
