### ISSUE TITLE
D01_Cat Texture

### ISSUE THREAD

**Issue by ToddlerPichu** [NaomiMod/Rent-A-Hero-No1#46]
> Regarding Cat texture please open a separate Issue, I'm fairly certain it refers to a wrong texture ID. The model needs to be found and patched. I'll pass it to our 3D modeller 👍 A save would be great, thanks.

What I believe to be Mrs. Tee's cat's texture is really messed up... this is present in the original JP version and consequentially the EN translation project, but I was hoping this was fixable. 
![shot82](https://user-images.githubusercontent.com/41944249/192677809-db0e937e-454f-4454-84cd-757a2044a306.png)
![shot115](https://user-images.githubusercontent.com/41944249/192677870-fa90d602-575e-4ebe-9b8b-d4e6fbc42ba0.png)

**Comment by VincentNLOBJ** [comment]
![image](https://user-images.githubusercontent.com/71412899/193914282-cc6f2fb8-abc5-4838-9627-fb8b9f9e331a.png)
Cat texture is now known, but there are 2 more instances where this texture is used.

Have you found any other cats in the game @ToddlerPichu @Guimli355 ?

**Comment by ToddlerPichu** [comment]
While it is possible I've missed one, forgotten or have not progressed far enough... I don't believe I have seen another cat, no

**Comment by Guimli355** [comment]
As ToddlerPichu, I don't remember seeing another cat...

**Comment by VincentNLOBJ** [comment]
![image](https://user-images.githubusercontent.com/71412899/194408593-dc62ff58-8536-4a9e-86d2-ea1a76e5098a.png)
![image](https://user-images.githubusercontent.com/71412899/194408660-67a11066-399a-4bb0-ad23-ba04f1b8c5f1.png)
Success! Egregiousguy successfully RE the format, next step will be to:
- Create a new texture (yeah no cat texture!)
- Redo all messy U/V keeping index order
- Create a script to reimport U/V floats according to new .obj

**Comment by VincentNLOBJ** [comment]
Here's the new cat texture I've made @Guimli355 @ToddlerPichu 
![immagine](https://user-images.githubusercontent.com/71412899/194749459-809e39be-2cd2-4eb7-84ec-81fc6d5853bf.png)



We are hard at work to fix it to work in game since also the original angle is wrong!
![immagine](https://user-images.githubusercontent.com/71412899/194749296-c2d44bb6-6d85-4201-a8f2-8e34382beb9e.png)

**Comment by Guimli355** [comment]
It looks already perfect to me. It's funny to think that nobody will pay attention to the cat, not knowing the job you did.

**Comment by VincentNLOBJ** [comment]
![immagine](https://user-images.githubusercontent.com/71412899/194775888-6dc404f5-2cb8-4154-82b1-19c2a2b7ea7f.png)
Done!
