### ISSUE TITLE
A06_Mieu's Job description for Patrol Clean Bay

### ISSUE THREAD

**Issue by ToddlerPichu** [NaomiMod/Rent-A-Hero-No1#47]
After accepting Patrol Clean Bay when checking its description both on the creamcast or through the R trigger, the text is spilling outside the box
![shot121](https://user-images.githubusercontent.com/41944249/192678508-3c89c32f-bda3-4778-8997-8c36b97ad5ee.png)
![shot118](https://user-images.githubusercontent.com/41944249/192678530-06519815-7738-407b-bf85-2f35b7356912.png)

**Comment by VincentNLOBJ** [comment]
![CM1l1Tw 1](https://user-images.githubusercontent.com/71412899/193346726-4d8c3def-b28d-4da6-a681-d6b5269ec77d.gif)

**Comment by ToddlerPichu** [comment]
@VincentNLOBJ  You may have posted the wrong .gif for this topic

**Comment by VincentNLOBJ** [comment]
Yup, wrong!
Ok just fixed text issue!
