### ISSUE TITLE
A02_left flyer number

### ISSUE THREAD

**Issue by Guimli355** [NaomiMod/Rent-A-Hero-No1#5]
Flyer that are left don't appear.
![IMG_20220921_231101](https://user-images.githubusercontent.com/113843539/191616430-2f43e065-f00d-446c-af72-1811883d05c3.jpg)

**Comment by VincentNLOBJ** [comment]
Does this happen when delivering flyers to other npcs too?

**Comment by Guimli355** [comment]
Yes, not only this one. It happens with all the npc.

Le jeu. 22 sept. 2022, 8:17 AM, VincentNL ***@***.***> a
écrit :

**Comment by VincentNLOBJ** [comment]
Wrong text, fixed it.

**Comment by VincentNLOBJ** [comment]
An issue with Scenario editor resulted into a number of variables being skipped. (showing empty space instead of variable)
I'm currently remapping / reassigning them.
![immagine](https://user-images.githubusercontent.com/71412899/193467655-263f1bb8-de8f-4a83-a617-b0d0648b027e.png)
