### ISSUE TITLE
A07_ Mom'N'Pop Sign untranslated

### ISSUE THREAD

**Issue by ToddlerPichu** [NaomiMod/Rent-A-Hero-No1#51]
Signs same as the JP version on the outside (on top, to the side, on door) and on the inside (door)... inside has 2 textures correct and translated
![shot136](https://user-images.githubusercontent.com/41944249/192861956-0cdc158e-225a-4ec4-a2c7-21a288515ec9.png)
![shot137](https://user-images.githubusercontent.com/41944249/192862719-e25826f8-9f2a-4997-8fc9-b69b5f7bad74.png)

**Comment by VincentNLOBJ** [comment]
Got it thanks, we did translate it without realizing it's were an actual shop. Great find!

**Comment by VincentNLOBJ** [comment]
Inside and outside (including reflection)
![immagine](https://user-images.githubusercontent.com/71412899/193415542-7ac89624-8ac9-4148-ad9b-d4813bb8385e.png)
