### ISSUE TITLE
A07_Fanny Hay Sign

### ISSUE THREAD

**Issue by ToddlerPichu** [NaomiMod/Rent-A-Hero-No1#52]
While different from the JP version, Fanny Hay's shop sign is not accurate to the in games shop name
Translation Project Sign:
![shot134](https://user-images.githubusercontent.com/41944249/192864101-2dd5a713-6c5b-4a70-adfb-5109ef624187.png)
JP Original Sign:
![shot135](https://user-images.githubusercontent.com/41944249/192864146-3f5f13a0-ed06-41d5-aba4-3d4064d1b637.png)

**Comment by VincentNLOBJ** [comment]
Got it thanks, we did translate it without realizing it's were an actual shop. Great find!

**Comment by VincentNLOBJ** [comment]
![immagine](https://user-images.githubusercontent.com/71412899/193410038-c6c32245-b0ff-4a25-b8cc-9cbac24f12b9.png)
