### ISSUE TITLE
A07_Shoddy Construction Sign

### ISSUE THREAD

**Issue by ToddlerPichu** [NaomiMod/Rent-A-Hero-No1#53]
The sign for Shoddy Construction was unlocalized and unchanged from the JP version
![shot140](https://user-images.githubusercontent.com/41944249/192865683-0b366c7c-a1da-43e4-8777-8dd1f03aa829.png)

**Comment by VincentNLOBJ** [comment]
![immagine](https://user-images.githubusercontent.com/71412899/193417450-3413b416-3da8-47f1-81bd-3ead274a379d.png)
