### ISSUE TITLE
A07_Voice Recorder text_Fannie Hay

### ISSUE THREAD

**Issue by ToddlerPichu** [NaomiMod/Rent-A-Hero-No1#55]
When using the Voice Recorder from your inventory you get text different text from when you first find it with inconsistencies, one is that incorrectly spells "Fanny Hay" and "Fannie Hay", another is that atleast in my opinion the talk a fortune card is not phrased coherently... and then final sentence "Message" could be capitalized here and I believe "I'llbe" is missing a space
![shot148](https://user-images.githubusercontent.com/41944249/192885932-49e9998a-8f69-423d-8656-c67e51fff526.png)
![shot149](https://user-images.githubusercontent.com/41944249/192888306-ffc45cfb-bbf5-442b-9c0f-fa64260e0c69.png)
![shot151](https://user-images.githubusercontent.com/41944249/192888312-621396d8-0ba6-45bf-b7df-f091eb4fc0db.png)

**Comment by VincentNLOBJ** [comment]
How about this?
![immagine](https://i.imgur.com/e1ZTqFj.gif)

**Comment by ToddlerPichu** [comment]
What about changing 
>Once inside, you must purchase a
Fortune Card, that will tell you
where to obtain the Invitation Card.

to
>Once inside, you must purchase the
correct Fortune Card, that tells you
where to obtain the Invitation Card.

if formatting allows, perhaps that would make it a bit clearer that you may need to purchase a few... since the line about needing a specific point card has been removed? Otherwise it all looks good, even if my idea is not taken into consideration or formatting doesn't allow.

**Comment by VincentNLOBJ** [comment]
Point 0 card were a text error, but in this quest you need to buy multiple fortune cards, right?

**Comment by ToddlerPichu** [comment]
Yes, you may need buy multiple, As it is random if you get a common joke message or a plot relevant message that moves along the story.

**Comment by VincentNLOBJ** [comment]
There's an entire chunk specific to steel points rimelicks (I though they were unused HiPPs messages for fortune telling machine in GIGO), does these messages show up there?

**Comment by VincentNLOBJ** [comment]
Gotcha 👍

**Comment by ToddlerPichu** [comment]
On second inspection, the JP version does not have what I assumed were joke messages in EN. The have actual fortunes, so the HiP-PPs here is a mistake.

**Comment by VincentNLOBJ** [comment]
Yes it's a mistake.
I'll remove HiP-PPs refs!

**Comment by ToddlerPichu** [comment]
Do you need a save to Fanny Hay's or do you have this covered from this point?

**Comment by VincentNLOBJ** [comment]
That'd be great, Thank you!

**Comment by ToddlerPichu** [comment]
Here is a save that should lead you directly to Fanny Hay on exit of convenient store
[RENTA1___003.zip](https://github.com/NaomiMod/Rent-A-Hero-No1/files/9678900/RENTA1___003.zip)

**Comment by VincentNLOBJ** [comment]
👍

**Comment by VincentNLOBJ** [comment]
How about this?
![CM1l1Tw 1](https://user-images.githubusercontent.com/71412899/193347384-83f19458-6b3e-4281-bebc-6ff696845948.gif)

**Comment by ToddlerPichu** [comment]
After the "You got a" should be a "..." ellipsis instead of ".." and you're missing a quotation after **dog house.**, everything else looks good to me as a way to not translate the JP fortunes. I like it

**Comment by VincentNLOBJ** [comment]
Done!
Thanks for your feedback!

**Comment by ToddlerPichu** [comment]
Sorry to reopen, but I see 2 mistakes on the new build. The rest of the fortunes should have ellipsis as well instead of double periods and the quotation mark should be after the period in "dog house." It should read:
```
You got a... Special message!
"You'll find what you're looking for 
in the dog house."
```
and the rest should read
```
You got a...
____ Fortune Card.
```
![shot345](https://user-images.githubusercontent.com/41944249/193431533-eefc1b2d-6c9c-49b3-8660-f2ced9d14979.png)
![shot353](https://user-images.githubusercontent.com/41944249/193431543-81e8c153-8811-4bb8-9dc6-8982dc4c8fb2.png)

**Comment by VincentNLOBJ** [comment]
1) You got a...
2) You got a... Special message!
"You'll find what you're looking for 
in the dog house."

Done for good!
