### ISSUE TITLE
A03_& e coli cola

### ISSUE THREAD

**Issue by Guimli355** [NaomiMod/Rent-A-Hero-No1#6]
On the burger shop, in the first menu it's written "& e coli cola". Is the "e"  to much or should it be replaced by "a". Sorry for the picture quality.
![IMG_20220921_230310](https://user-images.githubusercontent.com/113843539/191682098-d8670718-2028-482d-b983-2ce393090831.jpg)

**Comment by ToddlerPichu** [comment]
I do believe "e coli cola" is correct (reference to Escherichia coli, also known as E. coli), though the E in "e coli cola" could be capitalized if nitpicky. Either way "e" should not be replaced with "a"

**Comment by Guimli355** [comment]
Sorry, I didn't see that you already wrote E.coli  in your comment.

**Comment by VincentNLOBJ** [comment]
Wrong text, were supposed to be:
`Cona-Cola`
Fixed, thanks guys!
