### ISSUE TITLE
A10_ Mail I Was Really Saved! translation

### ISSUE THREAD

**Issue by ToddlerPichu** [NaomiMod/Rent-A-Hero-No1#63]
In this received mail "I Was Really Saved!" after completing the job, you are given a mail with very awkward to read translation of "レンタ ヒーロー の おかげ で 生き埋め の まま 死な ず に 助かっ た ぜ !" including "I didn't die to death" and "We managed to avoid caving!"
![shot176](https://user-images.githubusercontent.com/41944249/193038415-b7e1874a-cc53-4ee3-b3b7-2fa8b33030b9.png)

**Comment by VincentNLOBJ** [comment]
![immagine](https://user-images.githubusercontent.com/71412899/193116418-203c047b-83cb-449f-91a1-da8c787974f4.png)
