### ISSUE TITLE
A12_Question Mark

### ISSUE THREAD

**Issue by ToddlerPichu** [NaomiMod/Rent-A-Hero-No1#66]
The "?" on the first question you get walking Sofia to school as a bodyguard is on a separate line
![shot187](https://user-images.githubusercontent.com/41944249/193060004-27ae6881-465a-4b12-a939-7db6fcd4f80e.png)

**Comment by ToddlerPichu** [comment]
> Just taking the chance to express my gratitude for such detailed and quality reporting! Bravissimo! 💯

It is a honour to be part of the team... naturally I want to do my best on our project, so I express my gratitude as well for you and everyone else who have taken the game to the state it is in before me

**Comment by VincentNLOBJ** [comment]
fixed!
