### ISSUE TITLE
A12_even I didn't even understand

### ISSUE THREAD

**Issue by ToddlerPichu** [NaomiMod/Rent-A-Hero-No1#67]
When answering all question correctly you get text that uses 2 instances of "even"... either location they are in read fine to me "There were some questions even I didn't understand" or "There were some questions I didn't even understand" though I'm not sure which is most grammatically correct, but having both instances in the sentence does not make it read well in my opinion.
![shot188](https://user-images.githubusercontent.com/41944249/193068492-9fb086fb-b44e-48a6-b710-49e12a891c58.png)

**Comment by VincentNLOBJ** [comment]
Changed to:
```
There were some questions that
even I didn't understand!
Nice job!
```
