### ISSUE TITLE
A12_Sophia_TY Ultrasalaryman! mail

### ISSUE THREAD

**Issue by ToddlerPichu** [NaomiMod/Rent-A-Hero-No1#69]
Same as issue #68 where Sofia is spelled Sophia only if you fail in beating the kidnappers it is different mail for Ultrasalaryman
![shot192](https://user-images.githubusercontent.com/41944249/193078328-b3ea40a0-82b3-4ce7-8a63-7770b69d9cd0.png)

**Comment by VincentNLOBJ** [comment]
All Sophia instances were corrected to `Sofia`.
