### ISSUE TITLE
A12_MASTER SHITAZE_no SECA highlight

### ISSUE THREAD

**Issue by ToddlerPichu** [NaomiMod/Rent-A-Hero-No1#70]
The mail you receive from Jack Hammer just after his mail "I DID IT!" is titled "MASTER SHITAZE!" which is gibberish and just romaji of JP title "マスターシタゼ"... it is possible as this is a follow up to I DID IT! that the mail should be title "I MASTERED IT!" in english, as "マスターしたぜ" would make some sense for that translation with the quirk of his bad typing. Though it is possible I am missing something between the translation of my 3 languages to get to english and there may be a better or accurate translation... but I can say for sure "MASTER SHITAZE!" is not correct

There is also 1 instance of "SECA" not being highlighted in green in the mail
![shot198](https://user-images.githubusercontent.com/41944249/193100547-ef4382b5-18e7-4651-a36d-a4e6cd3c5b07.png)

**Comment by Guimli355** [comment]
I think you are right with your translation.
By the way, who is Jack Hammer? I receive email from him, but don't understand who he his ( sorry for polluting hear)

**Comment by ToddlerPichu** [comment]
I am not 100% sure myself who Jack Hammer is... all I know is you receive mail from him throughout the game as his writing improves and through context he is connected to the construction site, only his first messages appear a lot sooner than that part of the story come up. I have issues understanding the earlier messages both in JP and EN (though I suppose that is the point), so I am still unsure.

**Comment by Guimli355** [comment]
Fine, so it's normal to don't understand who he is, 🙏.
Does he speak a little french in the jap version too?

**Comment by VincentNLOBJ** [comment]
> Fine, so it's normal to don't understand who he is, 🙏. Does he speak a little french in the jap version too?
It's been adapted to sound like a French foreigner by our translator.

Fixed text with:
I MASTERED IT!

Also restored SECA green highlight
