### ISSUE TITLE
A21_Segata's love letter formatting

### ISSUE THREAD

**Issue by ToddlerPichu** [NaomiMod/Rent-A-Hero-No1#71]
When helping Segata write a love letter to Ms. Naomi atleast 1 of the options results in incorrect formatting. It is possible more or all combinations result in the improper formatting, this is just the one I have found first try... I suspect all of them could have this issue though.
I will update this report if needed as I find other formatting issues related to love letter... but I do not have the time to follow up with all options right away currently
![shot218](https://user-images.githubusercontent.com/41944249/193143433-dd708c6f-666d-4f5b-9e52-b93a899c698f.png)

**Comment by VincentNLOBJ** [comment]
Should be fixed now.
