### ISSUE TITLE
B03_Pizza job formatting

### ISSUE THREAD

**Issue by ToddlerPichu** [NaomiMod/Rent-A-Hero-No1#72]
When accepting the side job to deliver pizza your delivery instructions cut a word in half
![shot222](https://user-images.githubusercontent.com/41944249/193316456-4d4d9886-c32c-46de-afec-449df6d63203.png)

**Comment by ToddlerPichu** [comment]
This issue comes up for all orders and possibly more if it randomizes where and which pizzas go
![shot223](https://user-images.githubusercontent.com/41944249/193316830-e60abf70-7506-4521-a211-7cd337ae1cd5.png)
![shot224](https://user-images.githubusercontent.com/41944249/193316838-77466f8e-fa60-43b1-88fe-ed059c7723b5.png)
![shot225](https://user-images.githubusercontent.com/41944249/193316846-7dd466f4-3589-4cdd-80fc-5388ac7f26fa.png)

**Comment by VincentNLOBJ** [comment]
I'm on it!

**Comment by VincentNLOBJ** [comment]
Think it should be fixed now, but I cannot test it without a save atm!
If you prefer I could make a new bugfix release for you and Guimli :)

**Comment by ToddlerPichu** [comment]
I would love a new a new revision with bugfixes... that would allow me to test if the side quests function and all text is correct and I could confirm this is fixed. Though I can still provide a save file for you now if you would like to check yourself if this is fixed

**Comment by VincentNLOBJ** [comment]
Sure, if you have the save around I can test it.
Tomorrow I'll make a new private build for you guys!

**Comment by ToddlerPichu** [comment]
A save is plenty easy... here is one right inside the hotel with the job already accepted, all you need to do is exit and head right to DoReMi and talk to pizza chef to encounter the text
[RENTA1___001.zip](https://github.com/NaomiMod/Rent-A-Hero-No1/files/9687626/RENTA1___001.zip)

**Comment by VincentNLOBJ** [comment]
Thank you for your save, it worked perfectly! 👍 

![immagine](https://user-images.githubusercontent.com/71412899/193406735-30a9f37c-6128-4d1b-bc1a-089211dc858c.png)
