### ISSUE TITLE
A12_Capitol of japan

### ISSUE THREAD

**Issue by Guimli355** [NaomiMod/Rent-A-Hero-No1#76]
In the test, during the Sinclair bodyguard mission, capital is spelled capitol.
![IMG_20220930_223158](https://user-images.githubusercontent.com/113843539/193354422-c09c72eb-a24e-4062-9462-19f299a9e25b.jpg)

**Comment by ToddlerPichu** [comment]
Amazing find Guimli... I never received that question

**Comment by Guimli355** [comment]
Ha ha it's hard to find some that you left.

**Comment by VincentNLOBJ** [comment]
Great find! Thank You! 👍
