### ISSUE TITLE
A few more missed textures

### ISSUE THREAD

**Issue by ToddlerPichu** [NaomiMod/Rent-A-Hero-No1#86]
These 2 in front of Be-Hi Companythat say "Hi-To" (third one I imagine is the same texture just not stretched... i included it anyways to be safe)
![shot254](https://user-images.githubusercontent.com/41944249/193366743-22e1b6f8-6d76-44e8-b597-f38c1d1ec539.png)
![shot255](https://user-images.githubusercontent.com/41944249/193366756-2a68e96d-cfdb-411f-8da1-e64b398817e2.png)
![shot257](https://user-images.githubusercontent.com/41944249/193366762-ab7a6876-740f-46ab-854b-453ab04b8aa1.png)

These 2 in the same picture that say "DoLeMe"... the 2nd one is so low texture its almost not worth noting, its the one with text just about the red and green "NEW" text
![shot258](https://user-images.githubusercontent.com/41944249/193367209-8a540470-a61f-49e2-a85c-e20e3b688479.png)

These 2 posters in Fanny Hay's shop... aren't very important and could be explained away as it being a rural shop, but thought I'd mention anyways
![shot259](https://user-images.githubusercontent.com/41944249/193367370-38bcbb90-b5c2-42fc-9fba-099ea9ad2b65.png)
![shot260](https://user-images.githubusercontent.com/41944249/193367374-2e0fb1a6-40d2-4870-88f5-e91a3d49396a.png)

**Comment by ToddlerPichu** [comment]
Another missed one I just ran into... the sign behind the guy says "DAHANE POLICE STATION" instead of DRIVEBY, there may be other instances of this as well
![shot262](https://user-images.githubusercontent.com/41944249/193369412-03d3ee24-b51b-49af-95c4-16ccd1d2b913.png)

**Comment by ToddlerPichu** [comment]
I was right, there was another one other place it said Dahane... floor texture 
![shot307](https://user-images.githubusercontent.com/41944249/193420593-7dd8cb3a-6471-4070-8a0b-9ec8782c5162.png)

**Comment by VincentNLOBJ** [comment]
![MAP_PACKAGE BIN_2892]
![MAP_PACKAGE BIN_3088](https://user-images.githubusercontent.com/71412899/193459117-9e8eb535-c0c0-43f8-a740-a9143d48bdb5.png)
![MAP_PACKAGE BIN_2425](https://user-images.githubusercontent.com/71412899/193459118-dc07d54f-2f76-49ff-b534-863b31d65e2a.png)
(https://user-images.githubusercontent.com/71412899/193459109-0caa95e6-45ab-4017-989c-16f343d55b4c.png)
![MAP_PACKAGE BIN_2406](https://user-images.githubusercontent.com/71412899/193459113-f5f369a9-abd4-41e4-816c-4d5117911ca1.png)
![MAP_PACKAGE BIN_2919](https://user-images.githubusercontent.com/71412899/193459114-77229194-c617-45cb-b463-c3b0721fb960.png)
![MAP_PACKAGE BIN_4493](https://user-images.githubusercontent.com/71412899/193459115-69d3bfb8-d252-4e20-acc9-018c0d7f9fa1.png)
