### ISSUE TITLE
A14_to ld

### ISSUE THREAD

**Issue by ToddlerPichu** [NaomiMod/Rent-A-Hero-No1#87]
Space between "to ld" where it shouldn't be
![shot261](https://user-images.githubusercontent.com/41944249/193368343-3d14250f-50b9-4b43-bd1b-765d09c0f9d6.png)

**Comment by VincentNLOBJ** [comment]
Root cause seems text alignment of " to " which gets separated regardless of what goes next to it!
I'll hunt this one down. 👍
