### ISSUE TITLE
A01_3_Henshin Tutorial, armour

### ISSUE THREAD

**Issue by ToddlerPichu** [NaomiMod/Rent-A-Hero-No1#9]
Henshin left untranslated again, also noticed inconsistency with armour vs armor used (both are correct, but only 1 type should be used. American spelling "armor" was previously used in song subtitles and other places like 'Super Energy Combat Armor' aka SECA, while "armour" is used here. )
![shot21](https://user-images.githubusercontent.com/41944249/191695736-ae74c5cc-cc8b-4efc-bbaa-25289673e73d.png)

**Comment by VincentNLOBJ** [comment]
Replaced all instances of Armour to Armor, plus Henshin refs. 👍
