### ISSUE TITLE
A14_alright vs all right

### ISSUE THREAD

**Issue by ToddlerPichu** [NaomiMod/Rent-A-Hero-No1#98]
Inconstancies in the use of alright vs all right... i have noticed this numerous times, but just now catching it by the same character in the same scene
![shot317](https://user-images.githubusercontent.com/41944249/193424116-40f86c51-46f6-4d7c-bea8-844538977018.png)
![shot318](https://user-images.githubusercontent.com/41944249/193424117-2994cf89-d112-481c-aec5-78cf6161383c.png)

**Comment by VincentNLOBJ** [comment]
How do you suggest to adjust it?

**Comment by ToddlerPichu** [comment]
Personally I would change all instances of "all right" to "alright"... "all right" may be formal use, but casual use "alright" is equally correct and has been used since the 1800's and it reads better. Plus it uses less letters and spaces, which is always a plus when making sure no lines are broken in limited space such as video game dialogue, which we've already seen happen.

So in short, my opinion is to change every "all right" to "alright" for space and readability reasons.

**Comment by VincentNLOBJ** [comment]
I've sent your feedback to translation team, cheers for pointing this out!

**Comment by ToddlerPichu** [comment]
It is a shame I was only made aware of this project so late that I was only able to be a betatester... I would have loved to be part of the translation team early on.

**Comment by VincentNLOBJ** [comment]
You're doing a fantastic job on this, luckily we have tools that automate text insertion! :)
All right --> Alright
